' Rafael: Galera, pelo UC1, eu acho que é um material
' por solicitação, mas não tenho certeza
' Pela UC12, não tenho certeza se a solicitacao de Cadastro só pode ser feita
' com uma solicitação de Compra, mas coloquei o CadastroMaterial -- Compra,
' porque parece ser o caso.


@startuml
'https://plantuml.com/class-diagram

Compra "0...*" -- Material
TipoMaterial -- "0...*" Material
CadastroMaterial -- "1" Material
CadastroMaterial -- Compra
Compra "0...*"-- "1" Funcionario
Compra -- GerenteArea
Compra -- "1" StatusEspecial
StatusEspecial -- GerenteArea

class TipoMaterial {
    String nome
    Boolean estaCadastrado
}

class Material {
    String nome
    String descricao
    String codigo
    Boolean estaCadastrado
    Integer estoque
    Integer minimoCompra
    Integer minimoEstoque
}



class Funcionario {
    Integer quotaMensal
}

class GerenteArea {

}


class CadastroMaterial {
    String funcionario
    Boolean aceitado
}


class StatusEspecial {
    Boolean especial
    String motivoSolicitante
    Boolean aprovado
    String motivoGerente

}

class Compra {
    String quantidade
    String emailObservadorInfra
    String status
    Date prazoEntrega
}

@enduml