' Rafael: Galera, pelo UC1, eu acho que é um material
' por solicitação, mas não tenho certeza
' Pela UC12, não tenho certeza se a solicitacao de Cadastro só pode ser feita
' com uma solicitação de Compra, mas coloquei o CadastroMaterial -- Compra,
' porque parece ser o caso.


@startuml SOMAES
'https://plantuml.com/class-diagram

' Compra "0...*" -- "1" Material
TipoMaterial "0...*" -- "0...*" Material
CadastroMaterial "1" -- MaterialCadastrado
Compra "0...*"-- "1" Funcionario
Compra -- "1" StatusEspecial
Material <|-- MaterialEspecial
Compra -- "0...1" MaterialEspecial
Material <|-- MaterialCadastrado
Compra -- "0...1" MaterialCadastrado

class TipoMaterial {
    String nome
}

class Material {
    String nome
    String descricao
}

class MaterialEspecial {
    String motivoSolicitacao
}

class MaterialCadastrado {
    String codigo
    Integer estoque
    Integer minimoCompra
    Integer minimoEstoque
}

class Funcionario {
    Integer quotaMensal
}


class CadastroMaterial {
    String funcionario
    Boolean aceitado
}


class StatusEspecial {
    Boolean aprovado
    String motivoGerente

}

class Compra {
    String quantidade
    String emailObservadorInfra
    String status
    Date prazoEntrega
}

@enduml